import { Users, FileText, DollarSign, Phone } from "lucide-react"

export const mockCustomers = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah@fashionboutique.com",
    phone: "+1 (555) 123-4567",
    company: "Fashion Boutique",
    status: "active",
    avatar: "/placeholder.svg?height=48&width=48",
    totalValue: "$2,450",
    lastContact: "2 days ago",
    servicesCount: "3",
    satisfaction: "4.8",
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "michael@techstartup.com",
    phone: "+1 (555) 987-6543",
    company: "Tech Startup Inc",
    status: "active",
    avatar: "/placeholder.svg?height=48&width=48",
    totalValue: "$5,200",
    lastContact: "1 week ago",
    servicesCount: "5",
    satisfaction: "4.9",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    email: "emily@localrestaurant.com",
    phone: "+1 (555) 456-7890",
    company: "Local Restaurant",
    status: "prospect",
    avatar: "/placeholder.svg?height=48&width=48",
    totalValue: "$0",
    lastContact: "3 days ago",
    servicesCount: "0",
    satisfaction: "N/A",
  },
  {
    id: "4",
    name: "David Brown",
    email: "david@consultingfirm.com",
    phone: "+1 (555) 321-0987",
    company: "Brown Consulting",
    status: "active",
    avatar: "/placeholder.svg?height=48&width=48",
    totalValue: "$8,900",
    lastContact: "5 days ago",
    servicesCount: "7",
    satisfaction: "4.7",
  },
]

export const mockTickets = [
  {
    id: "T001",
    title: "Website not loading properly",
    customer: "Sarah Johnson",
    description: "Customer reports that their website is loading slowly and some images are not displaying correctly.",
    status: "open",
    priority: "high",
    assignedTo: "Tech Support Team",
    createdDate: "2 hours ago",
  },
  {
    id: "T002",
    title: "Invoice payment inquiry",
    customer: "Michael Chen",
    description: "Customer has questions about payment methods and wants to update billing information.",
    status: "in-progress",
    priority: "medium",
    assignedTo: "Finance Team",
    createdDate: "1 day ago",
  },
  {
    id: "T003",
    title: "Service completion follow-up",
    customer: "David Brown",
    description:
      "Follow-up on recently completed business plan development service. Customer wants additional revisions.",
    status: "resolved",
    priority: "low",
    assignedTo: "CX Team",
    createdDate: "3 days ago",
  },
  {
    id: "T004",
    title: "New service consultation request",
    customer: "Emily Rodriguez",
    description: "Potential customer wants to schedule a consultation for restaurant marketing services.",
    status: "open",
    priority: "medium",
    assignedTo: "Sales Team",
    createdDate: "1 day ago",
  },
]

export const mockInvoices = [
  {
    id: "1",
    number: "INV-2024-001",
    customer: "Sarah Johnson",
    service: "Social Media Audit",
    amount: "$150",
    status: "paid",
    issueDate: "Jan 15, 2024",
    dueDate: "Jan 30, 2024",
    paymentMethod: "Credit Card",
    commission: "$22.50",
  },
  {
    id: "2",
    number: "INV-2024-002",
    customer: "Michael Chen",
    service: "Business Plan Development",
    amount: "$499",
    status: "pending",
    issueDate: "Jan 18, 2024",
    dueDate: "Feb 2, 2024",
    paymentMethod: null,
    commission: "$74.85",
  },
  {
    id: "3",
    number: "INV-2024-003",
    customer: "David Brown",
    service: "Marketing Strategy",
    amount: "$699",
    status: "paid",
    issueDate: "Jan 10, 2024",
    dueDate: "Jan 25, 2024",
    paymentMethod: "Bank Transfer",
    commission: "$104.85",
  },
  {
    id: "4",
    number: "INV-2024-004",
    customer: "Emily Rodriguez",
    service: "Website Development",
    amount: "$899",
    status: "overdue",
    issueDate: "Dec 28, 2023",
    dueDate: "Jan 12, 2024",
    paymentMethod: null,
    commission: "$134.85",
  },
]

export const mockCRMStats = [
  { title: "Total Customers", value: "1,247", change: "+23 this month", icon: Users },
  { title: "Active Tickets", value: "18", change: "5 resolved today", icon: FileText },
  { title: "Outstanding Invoices", value: "$12,450", change: "8 pending", icon: DollarSign },
  { title: "Calls This Week", value: "156", change: "+12% vs last week", icon: Phone },
]
